SeriesYear = true
Scene = true

[Templates]
Series = "{{ .Title }}{{if .Options.SeriesYear}} ({{ .Year }}){{end}} - {{ .Episode}}{{if EpisodeTitle}} - {{ .EpisodeTitle}}{{end}}{{if .Options.Scene }} ({{ .Scene }}){{end}}"
Film = "{{ .Title }} ({{ .Year }}){{if .Options.Scene }} ({{ .Scene }}){{end}}"

[Regex]
Series = '(?P<title>[\w\.]+)\.(?P<ep>S\d{2}E\d{2})\.(?P<eptitle>[\w\.-]+)(?P<scene>1080p.+)'
Film = '(?P<title>[\w\.]+)\.(?P<year>\d{4})\.(?P<scene>(?:2160|1080|720)p[\w\.-]+(?:[\w\.]))'

[Regex.Custom.Film]
# rarbg and yify
Generic =  '(?P<title>[\w\.]+)\.(?P<year>\d{4})\.(?P<scene>(?:2160|1080|720)p[\w\.-]+(?:[\w\.]))'

[Regex.Custom.Series]
# rarbg, yify, publichd
Generic = '(?P<title>[\w\.]+)\.(?P<ep>S\d{2}E\d{2})\.(?P<scene>(?:2160|1080|720)p[\w\.-]+(?:[\w\.]]))'